# Generated by Django 5.0.7 on 2024-08-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_projet_manger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
