# Generated by Django 5.0.7 on 2024-08-09 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_projet_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
