# Generated by Django 5.0.7 on 2024-08-09 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_projet_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
